export const RATING_STATUSES = {
  ACTIVE: "ACTIVE",
  FLAGGED: "FLAGGED",
  HIDDEN: "HIDDEN",
  REMOVED: "REMOVED",
};

export const POSITIVE_FEEDBACK_TAGS = [
  "POLITE",
  "PROFESSIONAL",
  "QUICK_DELIVERY",
  "GOOD_COMMUNICATION",
  "CAREFUL_HANDLING",
];

export const NEGATIVE_FEEDBACK_TAGS = [
  "DELIVERY_LATE",
  "COMMUNICATION_ISSUE",
  "RUDE_BEHAVIOUR",
  "HANDLING_ISSUE",
  "INSTRUCTIONS_IGNORED",
  "SAFETY_CONCERN",
  "OTHER",
];

export const ALL_FEEDBACK_TAGS = [
  ...POSITIVE_FEEDBACK_TAGS,
  ...NEGATIVE_FEEDBACK_TAGS,
];

export const RATING_WINDOW_DAYS = 7;
